Stages:
  Status:
    actions:
      - type: liquibase
        command: status
        cmdArgs: {verbose: true, changelog-file: changelog/changelog.xml}
  
  validation:
    actions:
      - type: liquibase
        command: validate
        cmdArgs: {changelog-file: changelog/changelog.xml}