globalVariables:
    DIFF_FILE: "${WORKSPACE}/DIFF_${ENVIRONMENT}.json"
    SNAPSHOT_FILE: "${WORKSPACE}/${SCHEMA_NAME}_Snapshot_${ENVIRONMENT}.json"
stages:
  Status:
    actions:
      - type: liquibase
        command: Status
        cmdArgs: {verbose: true, changeLogFile: "${changelog}"}
        
  update:
    actions:
      - type: liquibase
        command: update
        cmdArgs: {changeLogFile: "${changelog}", pro-global-strip-comments: "false"}

  snapshot:
    actions:
      - type: liquibase
        command: snapshot
        cmdArgs: {verbose: true, changeLogFile: "${changelog}", snapshot-format: "json"}
        globalArgs: { outputfile: "${SNAPSHOT_FILE}"}

endStage:
    actions:
      - type: liquibase
        command: history
        cmdArgs: {changeLogFile: "${changelog}"}