stages:
  Status:
    actions:
      - type: liquibase
        command: Status
        cmdArgs: {verbose: true, changeLogFile: ${changelog}}
        
  
  Validation:
    actions:
      - type: liquibase
        command: Validate
        cmdArgs: {changeLogFile: ${changelog}}
        