# JDBC connection settings
url=hashicorp,kv/data/liquibase/${DBType}/${envir}/${DB_NAME},url
username=hashicorp,kv/data/liquibase/DBACreds/${DBType}/${envir},username
password=hashicorp,kv/data/liquibase/DBACreds/${DBType}/${envir},password
driver=oracle.jdbc.OracleDriver
logLevel=info
vault.addr=${VAULT_ADDR}
vault.namespace=admin

# Tracking table properties
liquibase.liquibaseSchemaName=liquibase
liquibase.databaseChangelogTableName=${DB_NAME}_databasechangelog
liquibase.databaseChangelogLockTableName=${DB_NAME}_databasechangeloglock