# git related properties

baseUrl = https://github.com

# vault related properties
VAULT_ADDR = https://liquibase-public-vault-b7156aa0.5e239cd0.z1.hashicorp.cloud:8200

# Service Now related properties
SN_API = https://dev313863.service-now.com/api/now

SN_API_UPLOAD = https://dev313863.service-now.com/api/now/attachment/file

HTTP_PROXY = https://dev313863.service-now.com/api/now/

# Nexus Related Properties
NEXUS_ST = http://nexus-service:8081

NEXUS_PROD = http://nexus:8081

NEXUS_REPO = Liquibase-CICD


